import {
  EngineAPI,
  baseEndpointProps,
  baseUpdateEndpointProps,
  paginatedResponseSchema,
  paginatedResponseServerSchema
} from '..'
import {cleanJSON} from '@/core/utils/toolbox'
import {
  embellishmentListSchemas,
  embellishmentListServerSchemas,
  embellishmentSchemas,
  embellishmentServerSchemas,
  embellishmentUpdateServerSchemas
} from '../../embellishment'
import {handleAsyncFunction, snakeCaseObjectKeysToCamelCase} from '@/core/utils/toolbox'
import {z} from 'zod'

type ListForStyleProps = baseEndpointProps & {
  styleSlug: string
}

type ForStyleProps = ListForStyleProps & {
  embellishmentSlug: string
}

type UpdateEmbellishmentProps<T> = baseUpdateEndpointProps<T> & ForStyleProps 
// & {
//   payload: z.infer<typeof embellishmentUpdateServerSchemas>
// }

const embellishmentPaginatedServerSchema = paginatedResponseServerSchema(embellishmentListServerSchemas)
const embellishmentPaginatedSchema = paginatedResponseSchema(embellishmentListSchemas)

type EmbellishmentListReturnType<T extends baseEndpointProps> = T['returnServerSchemas'] extends true
  ? z.infer<typeof embellishmentPaginatedServerSchema>
  : z.infer<typeof embellishmentPaginatedSchema>

type EmbellishmentReturnType<T extends baseEndpointProps> = T['returnServerSchemas'] extends true
? z.infer<typeof embellishmentServerSchemas>
: z.infer<typeof embellishmentSchemas>
export class EmbellishmentsEndpoints {
  // eslint-disable-next-line no-unused-vars
  constructor(private readonly engineAPI: EngineAPI) {
  }

  list<T extends ListForStyleProps>(props: T): Promise<EmbellishmentListReturnType<T>> {
    console.log('listForStyle', props.styleSlug, this.engineAPI)
    return handleAsyncFunction(async () => {
      // const res = (await this.engineAPI.fetcher.call<Promise <Record<string, unknown>>>({
      //   path: `/v1/embellishments/style/${props.styleSlug}${props?.qs ? `?${props.qs}` : ''}`
      // })) as Record<string, unknown>
      const res = {
        'next_cursor': null,
        'count': 53,
        'results': [
          {
            'active': true,
            'type': 'frame',
            'name': 'emb_sfly_sb-frame-rec-round-corners-long',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/0af7a1a48a715a07a84b6e20a04f785b',
            'pattern': 'pattern-02-03',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 512,
            'height': 310,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': true,
            'stacking': 'front',
            'anchors': {
              'x0': 0.0242,
              'y1': 0.96,
              'x1': 0.9758,
              'y0': 0.04
            },
            'scale': 0.0,
            'compatible_colors': [],
            'id': '0af7a1a4-8a71-5a07-a84b-6e20a04f785b',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-celebrate-everyday',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/0e9333030a69546f9b1afe0ec7ea4133',
            'pattern': 'celebrate-everyday',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 57,
            'text': 'celebrate-everyday',
            'is_specific': false,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '0e933303-0a69-546f-9b1a-fe0ec7ea4133',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'background',
            'name': 'bg_rec_sfly_mb-solidblack',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/117e54dab99852f1a8b7741da12778d9',
            'pattern': 'bg-#000000',
            'primary_color': '#000000',
            'compatibles': [
              '117e54da-b998-52f1-a8b7-741da12778d9'
            ],
            'margin': 0,
            'width': 512,
            'height': 434,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [
              '#FFFFFF',
              '#C9C9C9'
            ],
            'id': '117e54da-b998-52f1-a8b7-741da12778d9',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'photo-corner',
            'name': 'emb_sfly_mb-sq-charcoal',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/141426c761c55cc299858fc8acc61304',
            'pattern': 'pattern-01-01',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 256,
            'height': 256,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'top-left',
            'orientations': [
              'top-left',
              'top-right',
              'bottom-left',
              'bottom-right'
            ],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': 'back',
            'anchors': {
              'x0': 0.15,
              'y0': 0.15
            },
            'scale': 0.25,
            'compatible_colors': [],
            'id': '141426c7-61c5-5cc2-9985-8fc8acc61304',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-photos',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/14fea84788495bd78e02ba7b94d7640a',
            'pattern': 'photos',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 512,
            'height': 97,
            'text': 'photos',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '14fea847-8849-5bd7-8e02-ba7b94d7640a',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-memories',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/1787c05dec5c5be8b806a4b0576863b3',
            'pattern': 'memories',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 512,
            'height': 75,
            'text': 'memories',
            'is_specific': false,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '1787c05d-ec5c-5be8-b806-a4b0576863b3',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-month',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/18feeb1f2bb45564916dbd2cecbf393d',
            'pattern': 'month',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 54,
            'text': 'month',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '18feeb1f-2bb4-5564-916d-bd2cecbf393d',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'frame',
            'name': 'emb_sfly_sb-frame-rec-round-corners',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/1bdafe1161e850689c144ea8a106e3cb',
            'pattern': 'pattern-02-01',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 512,
            'height': 384,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': true,
            'stacking': 'front',
            'anchors': {
              'x0': 0.02279577947320416,
              'y1': 0.9675695146519433,
              'x1': 0.9745387247392797,
              'y0': 0.02857647487800567
            },
            'scale': 0.0,
            'compatible_colors': [],
            'id': '1bdafe11-61e8-5068-9c14-4ea8a106e3cb',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-moments',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/1ca920710a465bfaa3b45f86c5e55dc1',
            'pattern': 'moments',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 512,
            'height': 78,
            'text': 'moments',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '1ca92071-0a46-5bfa-a3b4-5f86c5e55dc1',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'strip',
            'name': 'pb_sfly_blue',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/2911bea56b9e565bb49e9e5c14b8b3f4',
            'pattern': 'pattern-03-01',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 22,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '2911bea5-6b9e-565b-b49e-9e5c14b8b3f4',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-love',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/2af0b4a584aa543e9591cab2efd07a11',
            'pattern': '01-love',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 78,
            'text': '01-love',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '2af0b4a5-84aa-543e-9591-cab2efd07a11',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-summer-fun',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/2d2bcce292365806bb02959aec584230',
            'pattern': 'summer-fun',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 77,
            'text': 'summer-fun',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '2d2bcce2-9236-5806-bb02-959aec584230',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-favorite-photos',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/324b35a760695720833892fa0aaa0a34',
            'pattern': 'favorite-photos',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 78,
            'text': 'favorite-photos',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '324b35a7-6069-5720-8338-92fa0aaa0a34',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'strip',
            'name': 'pb_sfly_mb-ribboncyanthin',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/32a2d4742fe654a394ac03baf939a72a',
            'pattern': 'pattern-03-02',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 4,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '32a2d474-2fe6-54a3-94ac-03baf939a72a',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-best-year',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/33023f6628725cbd95c50b06e748bf9f',
            'pattern': 'best-year',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 29,
            'text': 'best-year',
            'is_specific': false,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '33023f66-2872-5cbd-95c5-0b06e748bf9f',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-friends-family',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/36ee2e3201135f2c9ab45151b3f7eb16',
            'pattern': 'friends-and-family',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 80,
            'text': 'friends-and-family',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '36ee2e32-0113-5f2c-9ab4-5151b3f7eb16',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'strip',
            'name': 'pb_sfly_mb-ribbonwhitemedium',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/37bcf4e0dbc852b9bd7dc81cfe1ead74',
            'pattern': 'pattern-03-04',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 13,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '37bcf4e0-dbc8-52b9-bd7d-c81cfe1ead74',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'band',
            'name': 'pb_sfly_mb-rec-charcoal',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/3d9bde85929e5cbb944e3461d4b46ea5',
            'pattern': 'pattern-02-01',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 158,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thick',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '3d9bde85-929e-5cbb-944e-3461d4b46ea5',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-our-family',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/41766524c3c55739a0790566759a575a',
            'pattern': 'our-family',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 90,
            'text': 'our-family',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '41766524-c3c5-5739-a079-0566759a575a',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'band',
            'name': 'pb_sfly_mb-rec-darkgrey',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/53c48258a46a5806b66e4f74efa588d7',
            'pattern': 'pattern-02-02',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 158,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thick',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '53c48258-a46a-5806-b66e-4f74efa588d7',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-live-love-laugh',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/6298b231307f51359f54823608dc3569',
            'pattern': 'live-love-laugh',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 18,
            'text': 'live-love-laugh',
            'is_specific': false,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '6298b231-307f-5135-9f54-823608dc3569',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-our-family-2',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/69c0c3bec49452268467f2198fd3cf10',
            'pattern': 'our-family',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 512,
            'height': 52,
            'text': 'our-family',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '69c0c3be-c494-5226-8467-f2198fd3cf10',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-family',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/6ea4c5e6909159ecb8810b50816933ca',
            'pattern': 'family',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 56,
            'text': 'family',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '6ea4c5e6-9091-59ec-b881-0b50816933ca',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'strip',
            'name': 'pb_sfly_mb-ribbonyellowthin',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/6f98a0ca90535ca3bac0873094e024d5',
            'pattern': 'pattern-03-06',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 4,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '6f98a0ca-9053-5ca3-bac0-873094e024d5',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-stories',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/759c59f434515c23b268cf1edb23d2b5',
            'pattern': 'stories',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 512,
            'height': 97,
            'text': 'stories',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '759c59f4-3451-5c23-b268-cf1edb23d2b5',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'band',
            'name': 'pb_sfly_blue',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/7ff48b06953b5066ab6851157bba2819',
            'pattern': 'pattern-03-01',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 22,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '7ff48b06-953b-5066-ab68-51157bba2819',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-our-moments',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/829909ed083b5b43a086a072527c8377',
            'pattern': 'our-moments',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 512,
            'height': 123,
            'text': 'our-moments',
            'is_specific': false,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '829909ed-083b-5b43-a086-a072527c8377',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-family-memories',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/852daff61faf544bb97f53e36f9ea71c',
            'pattern': 'family-memories',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 81,
            'text': 'family-memories',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '852daff6-1faf-544b-b97f-53e36f9ea71c',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-best-day-ever',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/8c8538a5682057b5bb3569ab72a9ce59',
            'pattern': 'best-day-ever',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 221,
            'text': 'best-day-ever',
            'is_specific': false,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '8c8538a5-6820-57b5-bb35-69ab72a9ce59',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'strip',
            'name': 'pb_sfly_mb-border-boxes-lt-gray',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/90864fc882cd53969c8d77e6db2fabf2',
            'pattern': 'pattern-04-01',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 17,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '90864fc8-82cd-5396-9c8d-77e6db2fabf2',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'strip',
            'name': 'pb_sfly_mb-ribbonwhitethin',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/92357c3ea4f158e2a01997571cf8f603',
            'pattern': 'pattern-03-05',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 4,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '92357c3e-a4f1-58e2-a019-97571cf8f603',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'band',
            'name': 'pb_sfly_mb-rec-white',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/9a1e320e5d385d0aa5c2cb22ebb43898',
            'pattern': 'pattern-02-04',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 158,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thick',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '9a1e320e-5d38-5d0a-a5c2-cb22ebb43898',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-home',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/9c5c0d95edbb56288a129ee22adc74a4',
            'pattern': 'home',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 66,
            'text': 'home',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '9c5c0d95-edbb-5628-8a12-9ee22adc74a4',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'band',
            'name': 'pb_sfly_mb-ribbonwhitewide',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/9cae856204f05befa984c6ce248fd9ed',
            'pattern': 'pattern-02-04',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 29,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '9cae8562-04f0-5bef-a984-c6ce248fd9ed',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-day',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/9e24ee615c3b5fa780f4d4ec47966922',
            'pattern': 'day',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 247,
            'height': 100,
            'text': 'day',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '9e24ee61-5c3b-5fa7-80f4-d4ec47966922',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-year',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/9ff76241a9d1542aa07457db2d472140',
            'pattern': 'year',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 75,
            'text': 'year',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': '9ff76241-a9d1-542a-a074-57db2d472140',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'strip',
            'name': 'pb_sfly_mb-ribbonwhitewide',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/a00e08791c985b8db9cee895b53b3b04',
            'pattern': 'pattern-02-01',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 29,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'a00e0879-1c98-5b8d-b9ce-e895b53b3b04',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'frame',
            'name': 'emb_sfly_sb-frame-sq-round-corners',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/a1e581ba98cd592da6035503136832db',
            'pattern': 'pattern-02-02',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 256,
            'height': 256,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': true,
            'stacking': 'front',
            'anchors': {
              'x0': 0.02729574611748814,
              'y1': 0.9654262854182006,
              'x1': 0.9677887747728539,
              'y0': 0.029433223407119125
            },
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'a1e581ba-98cd-592d-a603-5503136832db',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'strip',
            'name': 'pb_sfly_mb-dotswhite',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/afcbab05ade45b5896b7947dd23de3b7',
            'pattern': 'pattern-05-01',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 6,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'afcbab05-ade4-5b58-96b7-947dd23de3b7',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-hello',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/be179530e24056a6860435f0569fed13',
            'pattern': 'hello',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 512,
            'height': 97,
            'text': 'hello',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'be179530-e240-56a6-8604-35f0569fed13',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-on-the-road',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/beeb79cfacaf5c0888e1390467b11e3f',
            'pattern': 'on-the-road',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 92,
            'text': 'on-the-road',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'beeb79cf-acaf-5c08-88e1-390467b11e3f',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'photo-corner',
            'name': 'emb_sfly_mb-sq-charcoal',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/c899c75b7346533494f5f7928bd8ada5',
            'pattern': 'pattern-01-02',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 256,
            'height': 256,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'top-left',
            'orientations': [
              'top-left',
              'top-right',
              'bottom-left',
              'bottom-right'
            ],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': 'back',
            'anchors': {
              'x0': 0.15,
              'y0': 0.15
            },
            'scale': 0.25,
            'compatible_colors': [],
            'id': 'c899c75b-7346-5334-94f5-f7928bd8ada5',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'background',
            'name': 'bg_sq_sfly_mb-solidblack',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/cb593f56bcaa507fb7a518ae699cf3ef',
            'pattern': 'bg-#000000',
            'primary_color': '#000000',
            'compatibles': [
              'cb593f56-bcaa-507f-b7a5-18ae699cf3ef'
            ],
            'margin': 0,
            'width': 512,
            'height': 512,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [
              '#FFFFFF',
              '#C9C9C9'
            ],
            'id': 'cb593f56-bcaa-507f-b7a5-18ae699cf3ef',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'frame',
            'name': 'emb_sfly_mb-frame-rec-thin-white',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/cbaf3100f4ad5ae89e2357567431b57f',
            'pattern': 'pattern-01-01',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 256,
            'height': 186,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': true,
            'stacking': 'front',
            'anchors': {
              'x0': 0.03,
              'y1': 0.9588,
              'x1': 0.97,
              'y0': 0.0412
            },
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'cbaf3100-f4ad-5ae8-9e23-57567431b57f',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-love-thick',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/cc13f3e983ec557aba71de657ef1f850',
            'pattern': '02-love',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 59,
            'text': '02-love',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'cc13f3e9-83ec-557a-ba71-de657ef1f850',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-hello-spring',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/cdcc8cd0fc88540da546adf26d1c3eb2',
            'pattern': 'hello-spring',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 90,
            'text': 'hello-spring',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'cdcc8cd0-fc88-540d-a546-adf26d1c3eb2',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'photo-corner',
            'name': 'emb_sfly_sb-photo-corner',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/d3856c235ecc50ef8603ca9d5b2ca472',
            'pattern': 'pattern-02-01',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 151,
            'height': 150,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'top-left',
            'orientations': [
              'top-left',
              'top-right',
              'bottom-left',
              'bottom-right'
            ],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': 'front',
            'anchors': {
              'x0': 0.05,
              'y0': 0.05
            },
            'scale': 0.25,
            'compatible_colors': [],
            'id': 'd3856c23-5ecc-50ef-8603-ca9d5b2ca472',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-friends',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/d6d993bb8d515537945364a8491cac99',
            'pattern': 'friends',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 512,
            'height': 96,
            'text': 'friends',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'd6d993bb-8d51-5537-9453-64a8491cac99',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'text-sticker',
            'name': 'emb_sfly_mb-text-love-thin',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/da48c27e054f5d47b007da4e28d6e9cd',
            'pattern': '03-love',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 1,
            'width': 256,
            'height': 63,
            'text': '03-love',
            'is_specific': true,
            'min_surface': 0.03,
            'max_surface': 0.11,
            'orientation': '',
            'orientations': [],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'da48c27e-054f-5d47-b007-da4e28d6e9cd',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'photo-corner',
            'name': 'emb_sfly_sb-photo-corner',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/dee138cbb251551484832b2ba9d10a0e',
            'pattern': 'pattern-02-02',
            'primary_color': '#FFFFFF',
            'compatibles': [],
            'margin': 0,
            'width': 151,
            'height': 150,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'top-left',
            'orientations': [
              'top-left',
              'top-right',
              'bottom-left',
              'bottom-right'
            ],
            'thickness': '',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': 'front',
            'anchors': {
              'x0': 0.05,
              'y0': 0.05
            },
            'scale': 0.25,
            'compatible_colors': [],
            'id': 'dee138cb-b251-5514-8483-2b2ba9d10a0e',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'band',
            'name': 'pb_sfly_mb-rec-shilouette',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/e5e3246452b153fd8febe1b03c43db70',
            'pattern': 'pattern-02-03',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 158,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thick',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'e5e32464-52b1-53fd-8feb-e1b03c43db70',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'band',
            'name': 'pb_sfly_cw-diagonal-gray',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/f6736f2e1bd4503bb07c29a2add084ef',
            'pattern': 'pattern-01-01',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 51,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'f6736f2e-1bd4-503b-b07c-29a2add084ef',
            'style': 'modern-black-sfly'
          },
          {
            'active': true,
            'type': 'strip',
            'name': 'pb_sfly_mb-ribbonmagentathin',
            'url': 'https://mb-sls-engine-dev.s3.amazonaws.com/library/embs/fe08bb3523eb5370a2ce259b2acb4911',
            'pattern': 'pattern-03-03',
            'primary_color': '#C9C9C9',
            'compatibles': [],
            'margin': 0,
            'width': 1024,
            'height': 4,
            'text': '',
            'is_specific': false,
            'min_surface': 0.0,
            'max_surface': 0.0,
            'orientation': 'bottom',
            'orientations': [
              'top',
              'bottom',
              'left',
              'right'
            ],
            'thickness': 'thin',
            'h_flippable': false,
            'v_flippable': false,
            'rotatable': false,
            'stacking': '',
            'anchors': {},
            'scale': 0.0,
            'compatible_colors': [],
            'id': 'fe08bb35-23eb-5370-a2ce-259b2acb4911',
            'style': 'modern-black-sfly'
          }
        ]
      }
      return (props?.returnServerSchemas
        ? embellishmentPaginatedServerSchema.parse(res)
        : embellishmentPaginatedSchema.parse(snakeCaseObjectKeysToCamelCase(res))
      ) as EmbellishmentListReturnType<T>
    })
  }

  retrieve<T extends ForStyleProps>(props: T): Promise<EmbellishmentReturnType<T>> {
    return handleAsyncFunction(async () => {
      const res = (await this.engineAPI.fetcher.call<Promise <Record<string, unknown>>>({
        path: `/v1/embellishments/${props.embellishmentSlug}/style/${props.styleSlug}${props?.qs ? `?${props.qs}` : ''}`
      })) as Record<string, unknown>
      return (props?.returnServerSchemas
        ? embellishmentServerSchemas.parse(res)
        : embellishmentSchemas.parse(snakeCaseObjectKeysToCamelCase(res))
      ) as EmbellishmentReturnType<T>
    })
  }

  update<T extends UpdateEmbellishmentProps<z.infer<typeof embellishmentUpdateServerSchemas>>>(props: T):
   Promise<EmbellishmentReturnType<T>> {
    return handleAsyncFunction(async () => {
      const res = (await this.engineAPI.fetcher.call<Promise <Record<string, unknown>>>({
        path: `/v1/embellishments/${props.embellishmentSlug}/style/${props.styleSlug}`,
        options: {
          method: 'PUT',
          body: cleanJSON(props.payload)
        }
      })) as Record<string, unknown>
      return (props?.returnServerSchemas
        ? embellishmentServerSchemas.parse(res)
        : embellishmentSchemas.parse(snakeCaseObjectKeysToCamelCase(res))
      ) as EmbellishmentReturnType<T>
    })
  }

}
